### ISSUE TITLE
Strange frames

### ISSUE THREAD

**Issue by daswer123** [mayuelala/FollowYourEmoji#10]
Hi thanks for your code, I have a question, the output sometimes has strange frames that cause uncomfortable jerking of the picture.

I used my own picture and NPY example from inference_temple.

Is there any way to fix this?

https://github.com/user-attachments/assets/a45762f8-a5c7-43f3-a1f0-cd10858a0bbf

**Comment by daswer123** [comment]
https://github.com/user-attachments/assets/ff1111df-0caa-4868-9e30-5ae559a20b0c

**Comment by mayuelala** [comment]
you can check the overlap of long video generation. It seems no consistent.

**Comment by daswer123** [comment]
Can you tell me what I should pay attention to in the code, what part?

I am still new to this and would be glad if you could tell me where to look.

**Comment by j18655633156** [comment]
Hello,Good Question,I'm having the same problem.Did you find the problem? How should I change this code internally?
