### ISSUE TITLE
最大帧数是多少？

### ISSUE THREAD

**Issue by O-O1024** [mayuelala/FollowYourEmoji#21]
设置了 120帧就出错了，60帧可以

生成的视频有抖动、伪影

https://github.com/user-attachments/assets/456962fa-8635-4df8-bcd0-3640985c836f

https://github.com/user-attachments/assets/d51383b0-2807-42b8-ae0e-03af196270ac

**Comment by mayuelala** [comment]
这应该是长视频部分的设置有问题，可以换用另外一个函数
