### ISSUE TITLE
Possible Missing Files in Mediapipe Folder Leading to Import Failures for mediapipe.framework and mediapipe.task

### ISSUE THREAD

**Issue by lxxie298** [mayuelala/FollowYourEmoji#25]
Hi,

I'm encountering an issue when trying to import mediapipe.framework and mediapipe.task. It seems like some files might be missing from the mediapipe folder, causing the imports to fail.

I've followed the standard installation steps, but these specific modules are not available. Could you please check if any files were omitted from the repository?

Thank you!

**Comment by mayuelala** [comment]
have you solved this problem？
