### ISSUE TITLE
Training code?

### ISSUE THREAD

**Issue by jiaxilv** [mayuelala/FollowYourEmoji#5]

**Comment by adityapandey9** [comment]
Hi, @mayuelala Can you please tell us any approx time frame for this? Is it based on the "One-Shot Free-View Neural Talking Head Synthesis"? Thank you in advance :)

**Comment by mayuelala** [comment]
Thanks for attention, we are based on animate anyone, rather than mentioned paper.

**Comment by baopmessi** [comment]
Thank you for your awesome works. Could you please let me know the estimated release time for the training code?

**Comment by mayuelala** [comment]
#23
