### ISSUE TITLE
colab or huggingface demo please

### ISSUE THREAD

**Issue by loboere** [mayuelala/FollowYourEmoji#9]

**Comment by daswer123** [comment]
Hi, I made an implementation on google colab, works on free tier

https://github.com/daswer123/FollowYourEmoji-colab/blob/main/README.md

**Comment by mayuelala** [comment]
Thanks！ Can you merge it into our rep ？

**Comment by daswer123** [comment]
Yes, of course, I'm all for it if my work is useful )

Here's the notebook itself
https://github.com/daswer123/FollowYourEmoji-colab/blob/main/follow_emoji_collab.ipynb

I made some changes in the fork to make it work.

https://github.com/daswer123/FollowYourEmoji-colab/commit/3227c08374c429343818446afce9359f973d4b88
https://github.com/daswer123/FollowYourEmoji-colab/commit/273119d8a554e8d88f2bc051de4fc455d8fcbda8

You can modify the notebook as you like.
